export {default as Home} from './Home/Home'
export {default as Status} from './Status/Status'
export {default as Profile} from './Profile/Profile'
export {default as Explore} from './Explore/Explore'
export {default as Notifications} from './Notifications/Notifications'